import 'package:flutter/material.dart';
import 'screen_utils.dart';

class CustomSpacers {
  static final Widget height2 = SizedBox(height: 2.h);
  static final Widget height4 = SizedBox(height: 4.h);
  static final Widget height6 = SizedBox(height: 6.h);
  static final Widget height8 = SizedBox(height: 8.h);
  static final Widget height9 = SizedBox(height: 9.h);
  static final Widget height10 = SizedBox(height: 10.h);
  static final Widget height12 = SizedBox(height: 12.h);
  static final Widget height14 = SizedBox(height: 14.h);
  static final Widget height15 = SizedBox(height: 15.h);
  static final Widget height16 = SizedBox(height: 16.h);
  static final Widget height18 = SizedBox(height: 18.h);
  static final Widget height20 = SizedBox(height: 20.h);
  static final Widget height21 = SizedBox(height: 21.h);
  static final Widget height24 = SizedBox(height: 24.h);
  static final Widget height26 = SizedBox(height: 26.h);
  static final Widget height28 = SizedBox(height: 28.h);
  static final Widget height29 = SizedBox(height: 29.h);
  static final Widget height30 = SizedBox(height: 30.h);
  static final Widget height32 = SizedBox(height: 32.h);
  static final Widget height34 = SizedBox(height: 34.h);
  static final Widget height35 = SizedBox(height: 35.h);
  static final Widget height36 = SizedBox(height: 36.h);
  static final Widget height40 = SizedBox(height: 40.h);
  static final Widget height38 = SizedBox(height: 38.h);
  static final Widget height45 = SizedBox(height: 45.h);
  static final Widget height48 = SizedBox(height: 48.h);
  static final Widget height52 = SizedBox(height: 52.h);
  static final Widget height56 = SizedBox(height: 56.h);
  static final Widget height60 = SizedBox(height: 60.h);
  static final Widget height64 = SizedBox(height: 64.h);
  static final Widget height70 = SizedBox(height: 70.h);
  static final Widget height74 = SizedBox(height: 74.h);
  static final Widget height80 = SizedBox(height: 80.h);
  static final Widget height160 = SizedBox(height: 160.h);

  static final Widget width4 = SizedBox(width: 4.w);
  static final Widget width8 = SizedBox(width: 8.w);
  static final Widget width6 = SizedBox(width: 6.w);
  static final Widget width12 = SizedBox(width: 12.w);
  static final Widget width10 = SizedBox(width: 10.w);
  static final Widget width14 = SizedBox(width: 14.w);
  static final Widget width16 = SizedBox(width: 16.w);
  static final Widget width18 = SizedBox(width: 18.w);
  static final Widget width20 = SizedBox(width: 20.w);
  static final Widget width24 = SizedBox(width: 24.w);
  static final Widget width27 = SizedBox(width: 27.w);
  static final Widget width28 = SizedBox(width: 28.w);
  static final Widget width32 = SizedBox(width: 32.w);
  static final Widget width40 = SizedBox(width: 40.w);
  static final Widget width50 = SizedBox(width: 50.w);
}
