// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7j5Q8vXwsi7N5hmGuV4xJE6hsqwYtffU',
    appId: '1:34493646584:web:382dcf886182b7540f9d0d',
    messagingSenderId: '34493646584',
    projectId: 'zoozoovin-86d2e',
    authDomain: 'zoozoovin-86d2e.firebaseapp.com',
    storageBucket: 'zoozoovin-86d2e.appspot.com',
    measurementId: 'G-BET7J4HTZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBowgxXhNxqcjyEcsvwDHsFWraA_Qhb_7w',
    appId: '1:34493646584:android:28caab256a9de7df0f9d0d',
    messagingSenderId: '34493646584',
    projectId: 'zoozoovin-86d2e',
    storageBucket: 'zoozoovin-86d2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy-IzA37oLWQRb1MPf0yp0whjeghx_dMk',
    appId: '1:34493646584:ios:fde2b63dd7dac25d0f9d0d',
    messagingSenderId: '34493646584',
    projectId: 'zoozoovin-86d2e',
    storageBucket: 'zoozoovin-86d2e.appspot.com',
    iosBundleId: 'com.example.zoozoowin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy-IzA37oLWQRb1MPf0yp0whjeghx_dMk',
    appId: '1:34493646584:ios:fde2b63dd7dac25d0f9d0d',
    messagingSenderId: '34493646584',
    projectId: 'zoozoovin-86d2e',
    storageBucket: 'zoozoovin-86d2e.appspot.com',
    iosBundleId: 'com.example.zoozoowin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7j5Q8vXwsi7N5hmGuV4xJE6hsqwYtffU',
    appId: '1:34493646584:web:900273ea7f31db9c0f9d0d',
    messagingSenderId: '34493646584',
    projectId: 'zoozoovin-86d2e',
    authDomain: 'zoozoovin-86d2e.firebaseapp.com',
    storageBucket: 'zoozoovin-86d2e.appspot.com',
    measurementId: 'G-K8J32YZ4C0',
  );
}
